package com.hta.elevator.domain;
import java.math.BigDecimal;
import java.util.Date;

import com.hta.elevator.common.annotaion.EntityOperator;
import com.hta.elevator.common.annotaion.Excel;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
/**
 * 电梯表 Lift
 * 
 * @author sxx
 * @date 2020-11-30
 */
@ToString
@Setter
@Getter
@EntityOperator(operatorNaem = "电梯")
public class Lift
{
	/** 电梯ID */
	@Excel(name = "电梯ID")
	private Integer LiftId;
	/** 电梯基本ID */
	@Excel(name = "电梯基本ID")
	private Integer LiftBaseId;
	/** 自编号 */
	@Excel(name = "自编号")
	private Integer LID;
	/** 电梯编号 */
	@Excel(name = "电梯编号")
	private String LiftCode;
	/** 内部编码 */
	@Excel(name = "内部编码")
	private String InternalNo;
	/** 电梯名称 */
	@Excel(name = "电梯名称")
	private String LiftName;
	/** 电梯类型，1-直梯，2-扶梯 */
	@Excel(name = "电梯类型，1-直梯，2-扶梯")
	private Integer LiftType;
	/** FactoryNo */
	@Excel(name = "FactoryNo")
	private String FactoryNo;
	/** 注册代码 */
	@Excel(name = "注册代码")
	private String RegisterCode;
	/** VarietyCode */
	@Excel(name = "VarietyCode")
	private String VarietyCode;
	/** 设备品种 */
	@Excel(name = "设备品种")
	private String VarietyName;
	/** 制造厂商名称 */
	@Excel(name = "制造厂商名称")
	private String Manufacturer;
	/** 电梯出厂编号 */
	@Excel(name = "电梯出厂编号")
	private String ManufacturerNo;
	/** 设备安装日期 */
	@Excel(name = "设备安装日期")
	private Date InstallDate;
	/** 楼层数 */
	@Excel(name = "楼层数")
	private Integer Floor;
	/** 层站数 */
	@Excel(name = "层站数")
	private Integer Station;
	/** 不停站楼层 */
	@Excel(name = "不停站楼层")
	private String NotStopFloor;
	/** 额定速度 */
	@Excel(name = "额定速度")
	private BigDecimal Speed;
	/** 额定载重量 */
	@Excel(name = "额定载重量")
	private Integer LoadWeight;
	/** 机房类型：true-有机房，false-无机房 */
	@Excel(name = "机房类型：true-有机房，false-无机房")
	private Integer HasMachineRoom;
	/** ARD品牌，即停电应急装置品牌名称 */
	@Excel(name = "ARD品牌，即停电应急装置品牌名称")
	private String ARD;
	/** ARD投入使用时间 */
	@Excel(name = "ARD投入使用时间")
	private Date ARDDate;
	/** 省 */
	@Excel(name = "省")
	private String Province;
	/** 市 */
	@Excel(name = "市")
	private String City;
	/** 区县 */
	@Excel(name = "区县")
	private String Area;
	/** 详细地址 */
	@Excel(name = "详细地址")
	private String Address;
	/** 经度 */
	@Excel(name = "经度")
	private BigDecimal Lng;
	/** 纬度 */
	@Excel(name = "纬度")
	private BigDecimal Lat;
	/** 首次维保日期 */
	@Excel(name = "首次维保日期")
	private Date FirstUpkeepDate;
	/** 上次年检日期 */
	@Excel(name = "上次年检日期")
	private Date LastInspectionDate;
	/** 下次年检日期 */
	@Excel(name = "下次年检日期")
	private Date NextInspectionDate;
	/** 上次维保日期 */
	@Excel(name = "上次维保日期")
	private Date MaintenanceDate;
	/** 检验机构名称 */
	@Excel(name = "检验机构名称")
	private String Inspection;
	/** 维保单位ID */
	@Excel(name = "维保单位ID")
	private Integer McomId;
	/** 物业单位ID */
	@Excel(name = "物业单位ID")
	private Integer PcomId;
	/** 楼盘ID */
	@Excel(name = "楼盘ID")
	private Integer BuildId;
	/** 维保联系人1 */
	@Excel(name = "维保联系人1")
	private Integer MPersonnel1;
	/** 维保联系人1电话 */
	@Excel(name = "维保联系人1电话")
	private String MPersonnelPhone1;
	/** 维保联系人2 */
	@Excel(name = "维保联系人2")
	private Integer MPersonnel2;
	/** 维保联系人2电话 */
	@Excel(name = "维保联系人2电话")
	private String MPersonnelPhone2;
	/** 维保联系人3 */
	@Excel(name = "维保联系人3")
	private Integer MPersonnel3;
	/** 维保联系人3电话 */
	@Excel(name = "维保联系人3电话")
	private String MPersonnelPhone3;
	/** 物业联系人1 */
	@Excel(name = "物业联系人1")
	private Integer PPersonnel1;
	/** 物业联系人1电话 */
	@Excel(name = "物业联系人1电话")
	private String PPersonnelPhone1;
	/** 物业联系人2 */
	@Excel(name = "物业联系人2")
	private Integer PPersonnel2;
	/** 物业联系人2电话 */
	@Excel(name = "物业联系人2电话")
	private String PPersonnelPhone2;
	/** 物业联系人3 */
	@Excel(name = "物业联系人3")
	private Integer PPersonnel3;
	/** 物业联系人3电话 */
	@Excel(name = "物业联系人3电话")
	private String PPersonnelPhone3;
	/** 24小时值班电话 */
	@Excel(name = "24小时值班电话")
	private String DutyPhone;
	/** 分类代码 */
	@Excel(name = "分类代码")
	private Integer SortCode;
	/** 创建人 */
	@Excel(name = "创建人")
	private String CreatePerson;
	/** 修改人 */
	@Excel(name = "修改人")
	private String UpdatePerson;
	/** 分组ID */
	@Excel(name = "分组ID")
	private Integer GroupId;
	/** 创建者ID */
	@Excel(name = "创建者ID")
	private Integer CreateId;
	/** 创建时间 */
	@Excel(name = "创建时间")
	private Date CreateTime;
	/** 修改者ID */
	@Excel(name = "修改者ID")
	private Integer UpdateId;
	/** 修改时间 */
	@Excel(name = "修改时间")
	private Date UpdateTime;
	/** 在线时间 */
	@Excel(name = "在线时间")
	private Date OnlineTime;
	/** Enabled */
	@Excel(name = "Enabled")
	private Integer Enabled;
	/** 图片路径 */
	@Excel(name = "图片路径")
	private String ImagePath;
	/** LinkToGroupId */
	@Excel(name = "LinkToGroupId")
	private Integer LinkToGroupId;
	/** SecurityAdminiId */
	@Excel(name = "SecurityAdminiId")
	private Integer SecurityAdminiId;
	/** PolicyId */
	@Excel(name = "PolicyId")
	private Integer PolicyId;
	/** PolicyUpdateTime */
	@Excel(name = "PolicyUpdateTime")
	private Date PolicyUpdateTime;
	/** PolicyUpdateId */
	@Excel(name = "PolicyUpdateId")
	private Integer PolicyUpdateId;
}
